### ISSUE TITLE
ImportError: cannot import name 'start_carla' from 'sources'

### ISSUE THREAD

**Issue by KuldeepDileep** [rudrajit1729/Self-Driving-Car-CARLA#1]
Hello @rudrajit1729, when I execute your given train,py file I get the following error:
ImportError: cannot import name 'start_carla' from 'sources'

**Comment by rudrajit1729** [comment]
Hi @KuldeepDileep , Try importing carla from sources. Should work fine.

**Comment by KuldeepDileep** [comment]
Thank you @rudrajit1729 for your prompt response. 
After importing carla from sources I m getting the following error:
ImportError: cannot import name 'operating_system'

I am using Ubuntu 18.04 python 3.6 and Carla simulator provided by the Motion planning for self-driving car course on coursera.

**Comment by SExpert12** [comment]
Hi, are you able to run this code?
